CREATE TABLE Users (
	ID INT NOT NULL PRIMARY KEY ON CONFLICT REPLACE,
	TimezoneOffset INT,
	DaylightSavingsRegion INT NOT NULL DEFAULT 0
);

CREATE TABLE Guilds (
	ID INT NOT NULL PRIMARY KEY ON CONFLICT REPLACE,
	StreamingChannel INT
);

CREATE TABLE DefaultVoiceChannelNames (
	GuildID INT NOT NULL,
	ChannelID INT NOT NULL,
	ChannelName TEXT NOT NULL,
	PRIMARY KEY (GuildID, ChannelID) ON CONFLICT REPLACE
);

CREATE TABLE EmoteRegistry (
	UserID INT NOT NULL,
	EmoteID INT NOT NULL,
	EmoteName TEXT NOT NULL,
	Animated INT NOT NULL CHECK(Animated BETWEEN 0 AND 1) DEFAULT 0,
	PRIMARY KEY (UserID, EmoteID) ON CONFLICT REPLACE
);
